### ISSUE TITLE
Add wiredep support

### ISSUE THREAD

**Issue by DatTran** [christiannwamba/generator-wean#2]
It would be great to add wiredep support, to automatically include bower files:

Can I make a PR?

Basic changes:
```javascript
wiredep: {

          task: {

            src: [
                'app/public/views/*.ejs'
            ],

            options: {
                directory: 'app/public/libs'
            }
          }
        }
```

few more in app.js:
```javascript
app.set('views', path.join(__dirname, 'public/views'));
```

Probably have to add more code for development. But this allows for

```
grunt wiredep
grunt
```

Btw, thanks for making WEAN

**Comment by christiannwamba** [comment]
@DatTran My apologies for the late response. Please feel free to make a PR. Thanks

**Comment by christiannwamba** [comment]
No pull request from @DatTran so I am closing the issue. Feel free to re-open
