### ISSUE TITLE
Build doesn't find provided code

### ISSUE THREAD

**Issue by NicolasNeubauer** [christiannwamba/generator-wean#3]
After running grunt build on Win10, starting builds/nw_scaffold/win_[32|64]/nw.exe for me just opens a browser windows with a nwjs logo, not with the sample app.

**Comment by christiannwamba** [comment]
Hi @NicolasNeubauer I am yet to test on Windows 10. I will do so and get back. Thanks

**Comment by NicolasNeubauer** [comment]
Great, thanks for the quick reply. Let me know if I can help!

**Comment by christiannwamba** [comment]
@NicolasNeubauer Of course it is open source. Please fork and make pull request

**Comment by NicolasNeubauer** [comment]
Actually the same happens to me on MacOS. I do 
> yo wean 
> grunt build
and then when I start the application, it shows the nwjs logo, not the sample app.

Any idea what I'm doing wrong?

**Comment by NicolasNeubauer** [comment]
sorry didn't want to close

**Comment by NicolasNeubauer** [comment]
OK found the issue: If icon isn't there, the build doesn't finish. Will create a pull request. Would you prefer a doc change stating you need to have an icon before building, or adding empty icons?

**Comment by christiannwamba** [comment]
@NicolasNeubauer Yeah make a pull request. You could update the docs with both options
